### ISSUE TITLE
PHP errors on home page search

### ISSUE THREAD

**Issue by notartom** [LibriVox/librivox-catalog#106]
When searching from the home page (and only the home page), eg by typing "Mark Twain" in the search box on librivox.org and hitting Enter, the following 3 errors appear on the results page:

```
A PHP Error was encountered
Severity: Notice
Message: Undefined index: search_category
Filename: catalog/Search.php
Line Number: 96
```

```
A PHP Error was encountered
Severity: Notice
Message: Undefined index: search_category
Filename: catalog/Search.php
Line Number: 98
```

```
A PHP Error was encountered
Severity: Notice
Message: Undefined index: search_category
Filename: catalog/Search.php
Line Number: 100
```

**Comment by kgroeneveld** [comment]
Something is still broken with the search from the home page. No mater what you search for it ends up searching for "true". You can see the URL after submitting the search is `https://librivox.org/search/?q=true&search_form=advanced` and all the displayed results contain "true".

And now that I test the search from the catalog browse page it sometimes does the same thing but sometimes the search works fine. Not sure the exact sequence that triggers it to work or not work but the bug is probably related to the search from the home page never working.

And similarly when you click on the browse categories such as "Author" sometimes it ends up doing a search for "true" and sometimes it actually browses by author.
