### ISSUE TITLE
Some characters now not allowed in author date fields

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#154]
Trying to use a dash in the author date field (such as "ca. 1315-1325") or a slash (such as "1315/1325") results in the field not saving. Those are the only two characters discovered that are occasionally used.
This has only been an issue since the upgrades. It worked before.

**Comment by twinkietoes-on** [comment]
We also had a possible rejection of a period in an author name field. So:
- non-numerical characters in author birth/death year fields
- non-numerical characters in copyright & edition year fields
- periods in author name fields (possibly)

**Comment by notartom** [comment]
I believe it worked before the upgrade because the new version of the database software is more strict in what input it accepts (https://mariadb.com/kb/en/sql-mode/#strict_trans_tables). So previously, if a field in the database was listed as an integer, but the input was some alphanumeric string of characters, there would be some magic at the database level that would accept the input, possibly mangling it somewhat, or dropping that particular field altogether while still updating the other ones in the query (I'm not very knowledgeable about this, hence the handwavy "magic" explanation).

@garethsime's PR #169 is one way to address this, but it would mean author YOB and YOD would only be numbers. That would make sense to me, but I'm not sure if there's precedent for input other kinds of data into those fields.

**Comment by garethsime** [comment]
Yeah, my PR definitely doesn't solve the underlying problem, it just gives a better error message. (There were a couple of threads in the forum where people were expressing frustration that they were just getting a generic error message with no information on how to fix it.)

**Comment by twinkietoes-on** [comment]
There's definitely precedent for non-numeric characters in YOB and YOD fields: ca., BC or BCE, AD or CE, and fl. being the primary ones.

    On Saturday, September 9, 2023 at 05:29:46 p.m. EDT, Gareth Sime ***@***.***> wrote:  
 
 


Yeah, my PR definitely doesn't solve the underlying problem, it just gives a better error message. (There were a couple of threads in the forum where people were expressing frustration that they were just getting a generic error message with no information on how to fix it.)

**Comment by notartom** [comment]
(from PR #169)
> For the more technical explanation -- When we save the form generation, that all goes into the form_generators table. Any new authors that are created as part of the generator are saved into form_generators_authors, which has the auth_yob and auth_yod columns as four-digit integers. This doesn't align well with the actual authors table, which allows pretty much anything (varchar(10)), and I have no idea how people specify AD vs. BCE using the generator (negative, maybe?).

> There's definitely precedent for non-numeric characters in YOB and YOD fields: ca., BC or BCE, AD or CE, and fl. being the primary ones.

So that sounds like the solution is to make `auth_yob` and `auth_yod` in `form_generators_authors` `varchar(10)` to allow non-numeric characters as well, and to align them with `auth_yob` and `auth_yod` in `authors`.

**Comment by garethsime** [comment]
It looks like this has been fixed, at least it has the new column definitions in my copy of the database from a couple months ago
