### ISSUE TITLE
Remove Parentheses when Generating Filenames with Project Template

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#25]
If there are parentheses in a book title or author name, those parentheses are transferred to the suggested file name in the template. They should not transfer to the file name.

Priority: 1

**Comment by kgroeneveld** [comment]
I thought this would be a quick fix. But…

The current code black lists several special characters: ` `, `,`, `-`, `?`, `!`, `"`, `'`, `:`, `.`, `;`, `°`, `ª`.  It would be easy to add parenthesis to that list. But what about other special characters such as `@`, `#`, `$`, `&` or many more?

I wonder if instead of the code black listing certain characters if it should instead white list the allowed ones. The question then is what should that white list be?

Just `a-z` and `0-9`?

The file names have `_` between title and author and such but seem like they should be filtered out of title portion by default.

What about accents or other international characters? For accents they could be converted to non accented characters. But some international characters don’t have a simple conversion like that.
