### ISSUE TITLE
Order of links inconsistent across pages

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#47]
The top line on the web pages differs re: order of links and capitalization of the initial letter.
 
 Librivox Home Page
 About | Contact | Forum | Help
 
 Search / Reader / Book pages
 about | forum | contact | help

Priority: 3

**Comment by RayBB** [comment]
That is odd.
It looks like the lowercase ones come from here:
https://github.com/LibriVox/librivox-catalog/blob/44cb15ff3a6aab0d6ddcc3db3971090404674b08/application/views/catalog/partials/header.php#L49-L56

I don't see where the uppercase ones are coming from.
[Searching](https://github.com/LibriVox/librivox-catalog/search?q=contact) for "contact" only has 10 results and none seem to match.

**Comment by notartom** [comment]
I suspect it's because the home page is from the [WordPress theme](https://github.com/LibriVox/librivox-wordpress-theme) while everything else is from the catalog. They're made to appear like a single website by gluing them together with an [Apache config](https://github.com/LibriVox/librivox-ansible/blob/master/roles/blog%2Bcatalog/templates/librivox.org.conf#L62-L88) that could be described as either visionary or machiavellian, pick one ;)

**Comment by twinkietoes-on** [comment]
In which case, it makes the most sense to leave the home page alone and conform the others to the case and order of the ones on the home page.

**Comment by RayBB** [comment]
In that case, I can make a quick PR to update this
