### ISSUE TITLE
CodeIgniter: Error message in Project Launch results

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#90]
I created a group project. At the top of the resulting code was this:

```
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined offset: 0</p>
<p>Filename: project_launch/result_page.php</p>
<p>Line Number: 51</p>

</div>
```
Otherwise the process worked as expected.

**Comment by kgroeneveld** [comment]
The relevant line of code is `if ($translator[0])`. If you add a translator the error will probably go away. It does make me wonder why it worked before. That line of code should probably be `if (!empty($translator))` or something anyway.

**Comment by notartom** [comment]
I wonder if https://github.com/notartom/librivox-catalog/commit/4d9d09ccd7d9cac88ed9bda8cfad0354e30029c9 is somehow causing this...

**Comment by notartom** [comment]
Aha - looking at the POST request to https://librivox.org/add_project once the form has been filled out, the field that's being sent is `trans_id[1]`. It looks like `application/libraries/Form_generator_item.php` is what transforms these `trans_id[X]` into the `trans_list` that's used in the view. This transformation is conditional on `trans_id` existing in the POST data:

```php
        //translators
        if (isset($fields['trans_id']))
        {
            $this->_process_authors('trans', $fields);
```

So we need to change to something that checks for "are there fields that start with 'trans_id'?" I also suspect authors has the same problem, not sure why it's not being hit...

**Comment by kgroeneveld** [comment]
> I also suspect authors has the same problem, not sure why it's not being hit...

Maybe because the project launch form enforces that there is at least one author before you can submit it?

**Comment by notartom** [comment]
Actually, sticking a `print()` right after that `if isset` shows up in the page, so the conditional is somehow true (even if the field itself is `trans_id[0]`). So maybe your first idea was correct...

**Comment by notartom** [comment]
Addressed in https://github.com/notartom/librivox-catalog/commit/5fee26206e12e5516d06961d4cce55435ba38783.

**Comment by kgroeneveld** [comment]
>We're not sure how it ever worked, but this patch fixes it with an `isset`.

I figured out why it worked before.

In `public_html/index.php` the newer CodeIgniter enables more errors via the call to `error_reporting()`. If you set the error_reporting value more similar to previously then this error also goes away (or vice versa you can trigger the error in the master branch be enabling more error reporting).

This also explains why the typo fixed in 53919a6afc32feadc8d10deb6800e96bf976d682 didn’t cause complete failure of the validator before.

I think I prefer the extra error reporting, especially during development testing. I have actually been upping the error level during a lot of my testing already. It helps catch stupid mistakes like the typo mentioned above.

I actually get PHP errors all over the place now on the CI3 branch running on my PHP7 system and I suspect these mostly come down to the different level of error_reporting and “Step 10: Many functions now return NULL instead of FALSE on missing items”. I hope to look into each of these more soon. I wonder how many of them are outright bugs and how many are just questionable code that works anyway.

But first I think I want to continue going through the 20 step list of the CodeIgnitor upgrade process. I am up to about 15 (not that I fully understand everything up to that point).

**Comment by notartom** [comment]
Just a quick note in case I hadn't made it obvious before - the upgrade to
PHP7 is separate from the upgrade to CodeIgniter 3. The current plan is to
run CI3 on PHP5.6 (and that's what's currently being tested on the
staging/dev server) and then upgrade the OS (and the PHP version)
underneath.

**Comment by notartom** [comment]
With the upgrade complete, this can be closed.
