### ISSUE TITLE
CodeIgniter: Template not returning translation

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#97]
I made a Spanish solo; the template generated English rather than Spanish. 
(The form did change to Spanish as expected.)

A Dutch group project worked fine. 
A Spanish group project worked fine.
French solo worked fine.

I tested it on the live server; it worked normally.

**Comment by notartom** [comment]
Looks like I'll need handholding for this one. Here's what I'm doing to reproduce this:

1. Go to https://librivox.org/add_project
2. Fill in the required field (Title, Is this a compilation with multiple authors and sources?, Link to text, Recorded language, Author Last Name, Number of sections).
3. Hit Next! Generate my Forum Code!

Are you saying that the 'Recorded language' field should affect the language of the generated magic window? Because for me it never does: anything I put in there (English, Spanish, Italian, German) I always get the magic window template in English.

The only way I can affect the language of the MW is by changing the language dropdown near the top right - and that gives me a Spanish MW with no issues.

**Comment by twinkietoes-on** [comment]
I cannot the error now, either. 

It DID seem weird that it worked fine for other languages and types, but specifically not for Spanish solos. Maybe it was some weird cookie/cache issue.

> Are you saying that the 'Recorded language' field should affect the language of the generated magic window? Because for me it never does: anything I put in there (English, Spanish, Italian, German) I always get the magic window template in English.

No, it wasn't dependent on that field, and that wasn't what I was flagging. (It may be a debate if the "recorded language" field SHOULD affect the language generated, but you are correct - currently it does not.) :)

You can probably close this as a false alarm. 

[whine] It's difficult to tell sometimes what errors are "just" errors and what are CodeIgniter (or other specific engine) errors. And in this case, what is a legitimate error and what is just a general weirdness. [/whine]

**Comment by notartom** [comment]
With the upgrade complete, this can be closed.
