### ISSUE TITLE
Codeigniter: Tests in validator hanging

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#99]
I click "Run tests" on https://librivox.org/validator/13506

The spinny thing keeps spinning rather than returning the test results.

**Comment by notartom** [comment]
So actually that was d70f688b, and should be broken in production as well.

**Comment by kgroeneveld** [comment]
> should be broken in production as well.

That code definitely wouldn't work quite as intended but for whatever reason on my test server it does not cause the validator to hang. Maybe on you ci3 staging server there is a difference in the setup of the error handling? It would actually be nice to figure out how to make my test setup fail on this error so I would catch these types of mistakes easier.

**Comment by twinkietoes-on** [comment]
We've cataloged a few projects since the new code went live, and no one has complained about the tests hanging. 
    On Sunday, February 14, 2021, 5:52:09 p.m. EST, kgroeneveld <notifications@github.com> wrote:  
 
 



should be broken in production as well.


That code definitely wouldn't work quite as intended but for whatever reason on my test server it does not cause the validator to hang. Maybe on you ci3 staging server there is a difference in the setup of the error handling? It would actually be nice to figure out how to make my test setup fail on this error so I would catch these types of mistakes easier.

**Comment by notartom** [comment]
Not sure what to tell you - perhaps @kgroeneveld is correct, and that there's a difference in error reporting/debug settings between the dev and production servers. FWIW, the way I figured it out is using the Firefox dev tools to inspect the async POST request that's made when the 'Runs tests' (which... isn't that a typo, btw? And should be 'Run tests'?) button is clicked. The spinny thing keeps spinning because the server doesn't return what the page expects. Examining the response (still in dev tools), the cause of the error (the 'prject' typo) becomes obvious.
